package com.jen.async.contact;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jen.async.contact.Plaxo;

import com.jen.async.contact.PlaxoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig plaxoDaoConfig;

    private final PlaxoDao plaxoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        plaxoDaoConfig = daoConfigMap.get(PlaxoDao.class).clone();
        plaxoDaoConfig.initIdentityScope(type);

        plaxoDao = new PlaxoDao(plaxoDaoConfig, this);

        registerDao(Plaxo.class, plaxoDao);
    }
    
    public void clear() {
        plaxoDaoConfig.getIdentityScope().clear();
    }

    public PlaxoDao getPlaxoDao() {
        return plaxoDao;
    }

}
