package com.jen.async.contact;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NOTE".
 */
public class Note {

    private Long id;
    /** Not-null value. */
    private String contact_id;
    /** Not-null value. */
    private String display_name;
    /** Not-null value. */
    private String raw_contact_id;
    private String version;
    private String creation_time;
    private String last_time;

    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    public Note(Long id, String contact_id, String display_name, String raw_contact_id, String version, String creation_time, String last_time) {
        this.id = id;
        this.contact_id = contact_id;
        this.display_name = display_name;
        this.raw_contact_id = raw_contact_id;
        this.version = version;
        this.creation_time = creation_time;
        this.last_time = last_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getContact_id() {
        return contact_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContact_id(String contact_id) {
        this.contact_id = contact_id;
    }

    /** Not-null value. */
    public String getDisplay_name() {
        return display_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDisplay_name(String display_name) {
        this.display_name = display_name;
    }

    /** Not-null value. */
    public String getRaw_contact_id() {
        return raw_contact_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRaw_contact_id(String raw_contact_id) {
        this.raw_contact_id = raw_contact_id;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getCreation_time() {
        return creation_time;
    }

    public void setCreation_time(String creation_time) {
        this.creation_time = creation_time;
    }

    public String getLast_time() {
        return last_time;
    }

    public void setLast_time(String last_time) {
        this.last_time = last_time;
    }

    @Override
    public String toString() {
        return "Note{" +
                "id=" + id +
                ", contact_id='" + contact_id + '\'' +
                ", display_name='" + display_name + '\'' +
                ", raw_contact_id='" + raw_contact_id + '\'' +
                ", version='" + version + '\'' +
                ", creation_time='" + creation_time + '\'' +
                ", last_time='" + last_time + '\'' +
                '}';
    }
}
