package com.jen.async.contact;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PLAXO".
 */
public class Plaxo {

    private Long id;
    private String userid;
    private String regtime;
    private String actiontype;
    private String updatetime;
    private String states;
    /** Not-null value. */
    private String name;
    private String phone;
    private String workphone;
    private String homephone;
    private String photo;
    private String email;
    private String workemail;
    private String address;
    private String groups;
    private String custom;
    private String companynumber;
    private String departmentnumber;
    private String shortName;
    private String ou;
    private String titlenumber;
    private Integer raw_contacts_version;
    private Integer server_version;
    private Long creation_time;
    private String contact_id;
    private String raw_contact_id;
    private String org;

    public Plaxo() {
    }

    public Plaxo(Long id) {
        this.id = id;
    }

    public Plaxo(Long id, String userid, String regtime, String actiontype, String updatetime, String states, String name, String phone, String workphone, String homephone, String photo, String email, String workemail, String address, String groups, String custom, String companynumber, String departmentnumber, String shortName, String ou, String titlenumber, Integer raw_contacts_version, Integer server_version, Long creation_time, String contact_id, String raw_contact_id, String org) {
        this.id = id;
        this.userid = userid;
        this.regtime = regtime;
        this.actiontype = actiontype;
        this.updatetime = updatetime;
        this.states = states;
        this.name = name;
        this.phone = phone;
        this.workphone = workphone;
        this.homephone = homephone;
        this.photo = photo;
        this.email = email;
        this.workemail = workemail;
        this.address = address;
        this.groups = groups;
        this.custom = custom;
        this.companynumber = companynumber;
        this.departmentnumber = departmentnumber;
        this.shortName = shortName;
        this.ou = ou;
        this.titlenumber = titlenumber;
        this.raw_contacts_version = raw_contacts_version;
        this.server_version = server_version;
        this.creation_time = creation_time;
        this.contact_id = contact_id;
        this.raw_contact_id = raw_contact_id;
        this.org = org;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getRegtime() {
        return regtime;
    }

    public void setRegtime(String regtime) {
        this.regtime = regtime;
    }

    public String getActiontype() {
        return actiontype;
    }

    public void setActiontype(String actiontype) {
        this.actiontype = actiontype;
    }

    public String getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime;
    }

    public String getStates() {
        return states;
    }

    public void setStates(String states) {
        this.states = states;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getWorkphone() {
        return workphone;
    }

    public void setWorkphone(String workphone) {
        this.workphone = workphone;
    }

    public String getHomephone() {
        return homephone;
    }

    public void setHomephone(String homephone) {
        this.homephone = homephone;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getWorkemail() {
        return workemail;
    }

    public void setWorkemail(String workemail) {
        this.workemail = workemail;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getGroups() {
        return groups;
    }

    public void setGroups(String groups) {
        this.groups = groups;
    }

    public String getCustom() {
        return custom;
    }

    public void setCustom(String custom) {
        this.custom = custom;
    }

    public String getCompanynumber() {
        return companynumber;
    }

    public void setCompanynumber(String companynumber) {
        this.companynumber = companynumber;
    }

    public String getDepartmentnumber() {
        return departmentnumber;
    }

    public void setDepartmentnumber(String departmentnumber) {
        this.departmentnumber = departmentnumber;
    }

    public String getShortName() {
        return shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    public String getOu() {
        return ou;
    }

    public void setOu(String ou) {
        this.ou = ou;
    }

    public String getTitlenumber() {
        return titlenumber;
    }

    public void setTitlenumber(String titlenumber) {
        this.titlenumber = titlenumber;
    }

    public Integer getRaw_contacts_version() {
        return raw_contacts_version;
    }

    public void setRaw_contacts_version(Integer raw_contacts_version) {
        this.raw_contacts_version = raw_contacts_version;
    }

    public Integer getServer_version() {
        return server_version;
    }

    public void setServer_version(Integer server_version) {
        this.server_version = server_version;
    }

    public Long getCreation_time() {
        return creation_time;
    }

    public void setCreation_time(Long creation_time) {
        this.creation_time = creation_time;
    }

    public String getContact_id() {
        return contact_id;
    }

    public void setContact_id(String contact_id) {
        this.contact_id = contact_id;
    }

    public String getRaw_contact_id() {
        return raw_contact_id;
    }

    public void setRaw_contact_id(String raw_contact_id) {
        this.raw_contact_id = raw_contact_id;
    }

    public String getOrg() {
        return org;
    }

    public void setOrg(String org) {
        this.org = org;
    }

}
