package com.jen.async.contact;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PLAXO".
 */
public class Plaxo {

    private Long id;
    private String userid;
    private String regtime;
    /** Not-null value. */
    private String actiontype;
    private String updatetime;
    private String name;
    private String phone;
    private String workphone;
    private String homephone;
    private String photo;
    private String email;
    private String workemail;
    private String address;
    private String groups;
    private String custom;
    private Integer raw_contacts_version;
    private Integer server_version;
    private Long creation_time;
    private String contact_id;
    private String raw_contact_id;
    private String org;

    public Plaxo() {
    }

    public Plaxo(Long id) {
        this.id = id;
    }

    public Plaxo(Long id, String userid, String regtime, String actiontype, String updatetime, String name, String phone, String workphone, String homephone, String photo, String email, String workemail, String address, String groups, String custom, Integer raw_contacts_version, Integer server_version, Long creation_time, String contact_id, String raw_contact_id, String org) {
        this.id = id;
        this.userid = userid;
        this.regtime = regtime;
        this.actiontype = actiontype;
        this.updatetime = updatetime;
        this.name = name;
        this.phone = phone;
        this.workphone = workphone;
        this.homephone = homephone;
        this.photo = photo;
        this.email = email;
        this.workemail = workemail;
        this.address = address;
        this.groups = groups;
        this.custom = custom;
        this.raw_contacts_version = raw_contacts_version;
        this.server_version = server_version;
        this.creation_time = creation_time;
        this.contact_id = contact_id;
        this.raw_contact_id = raw_contact_id;
        this.org = org;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getRegtime() {
        return regtime;
    }

    public void setRegtime(String regtime) {
        this.regtime = regtime;
    }

    /** Not-null value. */
    public String getActiontype() {
        return actiontype;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setActiontype(String actiontype) {
        this.actiontype = actiontype;
    }

    public String getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getWorkphone() {
        return workphone;
    }

    public void setWorkphone(String workphone) {
        this.workphone = workphone;
    }

    public String getHomephone() {
        return homephone;
    }

    public void setHomephone(String homephone) {
        this.homephone = homephone;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getWorkemail() {
        return workemail;
    }

    public void setWorkemail(String workemail) {
        this.workemail = workemail;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getGroups() {
        return groups;
    }

    public void setGroups(String groups) {
        this.groups = groups;
    }

    public String getCustom() {
        return custom;
    }

    public void setCustom(String custom) {
        this.custom = custom;
    }

    public Integer getRaw_contacts_version() {
        return raw_contacts_version;
    }

    public void setRaw_contacts_version(Integer raw_contacts_version) {
        this.raw_contacts_version = raw_contacts_version;
    }

    public Integer getServer_version() {
        return server_version;
    }

    public void setServer_version(Integer server_version) {
        this.server_version = server_version;
    }

    public Long getCreation_time() {
        return creation_time;
    }

    public void setCreation_time(Long creation_time) {
        this.creation_time = creation_time;
    }

    public String getContact_id() {
        return contact_id;
    }

    public void setContact_id(String contact_id) {
        this.contact_id = contact_id;
    }

    public String getRaw_contact_id() {
        return raw_contact_id;
    }

    public void setRaw_contact_id(String raw_contact_id) {
        this.raw_contact_id = raw_contact_id;
    }

    public String getOrg() {
        return org;
    }

    public void setOrg(String org) {
        this.org = org;
    }

}
